export const TALENTS_4E=Object.freeze({
absoluteTimeSense:{label:"Absolute Time Sense",policy:"fixed",baseCost:3},ambidexterity:{label:"Ambidexterity",policy:"fixed",baseCost:3},bumpOfDirection:{label:"Bump Of Direction",policy:"fixed",baseCost:3},combatSense:{label:"Combat Sense",policy:"roll",baseCost:3,perLevel:2,characteristic:"INT"},cramming:{label:"Cramming",policy:"repeatable",baseCost:5},defenseManeuver:{label:"Defense Maneuver",policy:"fixed",baseCost:5},doubleJointed:{label:"Double Jointed",policy:"fixed",baseCost:3},eideticMemory:{label:"Eidetic Memory",policy:"fixed",baseCost:10},fastDraw:{label:"Fast Draw",policy:"roll",baseCost:3,perLevel:2,characteristic:"DEX"},lightningCalculator:{label:"Lightning Calculator",policy:"fixed",baseCost:3},lightsleep:{label:"Lightsleep",policy:"fixed",baseCost:3},luck:{label:"Luck",policy:"dice",baseCost:5},perfectPitch:{label:"Perfect Pitch",policy:"fixed",baseCost:3},resistance:{label:"Resistance",policy:"resistance",baseCost:1},simulateDeath:{label:"Simulate Death",policy:"fixed",baseCost:3},speedReading:{label:"Speed Reading",policy:"fixed",baseCost:3},universalTranslator:{label:"Universal Translator",policy:"roll",baseCost:20,perLevel:2,characteristic:"INT"}});
export const PERKS_4E=Object.freeze({
favor:{label:"Favor",policy:"fixed",baseCost:1},contact8:{label:"Contact (8−)",policy:"contact",baseCost:1,baseRoll:8},contact11:{label:"Contact (11−)",policy:"contact",baseCost:2,baseRoll:11},wellOff:{label:"Money: Well Off",policy:"fixed",baseCost:5},wealthy:{label:"Money: Wealthy",policy:"fixed",baseCost:10},filthyRich:{label:"Money: Filthy Rich",policy:"fixed",baseCost:15}});
export function calculateTalent4e(key,characteristics={},levels=0){const item=TALENTS_4E[key];if(!item)throw new Error("Unknown Fourth Edition talent: "+key);levels=Math.max(0,Number(levels)||0);let cost=item.baseCost,detail="";if(item.policy==="repeatable")cost=item.baseCost*Math.max(1,levels);if(item.policy==="dice"){cost=item.baseCost*Math.max(1,levels);detail=Math.max(1,levels)+"d6";}if(item.policy==="resistance"){levels=Math.max(3,levels);cost=levels;detail=levels+" resistance";}if(item.policy==="roll"){cost=item.baseCost+levels*item.perLevel;const roll=9+Math.floor(Number(characteristics[item.characteristic])/5+.5)+levels;detail=item.characteristic+" "+roll+"−";}return {key,label:item.label,levels,cost,detail,pricingBasis:"Fourth Edition"};}
export function calculatePerk4e(key,levels=0){const item=PERKS_4E[key];if(!item)throw new Error("Unknown Fourth Edition perk: "+key);levels=Math.max(0,Number(levels)||0);const cost=item.baseCost+(item.policy==="contact"?levels:0),detail=item.policy==="contact"?(item.baseRoll+levels)+"−":"";return {key,label:item.label,levels,cost,detail,pricingBasis:"Fourth Edition"};}
export function buildAbility4e({section,key,name,characteristics,levels=0,notes=""}){const mechanics=section==="talents"?calculateTalent4e(key,characteristics,levels):calculatePerk4e(key,levels);return {id:crypto.randomUUID(),tag:"CANONICAL",xmlId:key,name:name||mechanics.label,alias:mechanics.label,option:"",levels:Number(levels),baseCost:mechanics.cost,notes,mechanics,rawXml:""};}
const HDC_TALENTS={ABSOLUTE_TIME_SENSE:"absoluteTimeSense",AMBIDEXTERITY:"ambidexterity",BUMP_OF_DIRECTION:"bumpOfDirection",COMBAT_SENSE:"combatSense",CRAMMING:"cramming",DEFENSE_MANEUVER:"defenseManeuver",DOUBLE_JOINTED:"doubleJointed",EIDETIC_MEMORY:"eideticMemory",FAST_DRAW:"fastDraw",LIGHTNING_CALCULATOR:"lightningCalculator",LIGHTSLEEP:"lightsleep",LUCK:"luck",PERFECT_PITCH:"perfectPitch",RESISTANCE:"resistance",SIMULATE_DEATH:"simulateDeath",SPEED_READING:"speedReading",UNIVERSAL_TRANSLATOR:"universalTranslator"};
export function analyzeHdcTalent(rawXml,characteristics){if(!rawXml)return null;const node=new DOMParser().parseFromString(rawXml,"application/xml").documentElement,key=HDC_TALENTS[node.getAttribute("XMLID")];if(!key)return {status:"unsupported",display:"No verified Fourth Edition Talent mapping"};const result=calculateTalent4e(key,characteristics,Number(node.getAttribute("LEVELS")||0));return {...result,status:"converted",repricedFrom:"hero-designer-v3-5e-hdc"};}
export function analyzeHdcPerk(rawXml){if(!rawXml)return null;const node=new DOMParser().parseFromString(rawXml,"application/xml").documentElement,id=node.getAttribute("XMLID"),levels=Number(node.getAttribute("LEVELS")||0);if(id==="FAVOR")return {...calculatePerk4e("favor"),status:"converted",repricedFrom:"hero-designer-v3-5e-hdc"};if(id==="CONTACT"&&levels===1)return {...calculatePerk4e("contact8"),status:"converted",repricedFrom:"hero-designer-v3-5e-hdc"};if(id==="MONEY"){const key={WELLOFF:"wellOff",WEALTHY:"wealthy",FILTHYRICH:"filthyRich"}[String(node.getAttribute("OPTIONID")||node.getAttribute("OPTION")||"").toUpperCase()];if(key)return {...calculatePerk4e(key),status:"converted",repricedFrom:"hero-designer-v3-5e-hdc"};}return {status:"unsupported",display:"No verified Fourth Edition Perk mapping"};}
export function abilitySummary(entry){const a=entry.mechanics;if(!a)return "";if(a.status==="unsupported")return a.display;return [a.repricedFrom?"4e repriced":"",a.detail,a.cost+" points"].filter(Boolean).join(" · ");}
