import { characteristicCost, combatValue, figured, normalizeCharacter, primaryKeys, figuredKeys, roll3d6, rollNormalDamage, rollKillingDamage } from "./rules.js";
import { importHdc } from "./hdc.js";
import { getCharacter, loadCharacters, saveCharacter } from "./store.js";
let current=null; let installPrompt=null;
const $=(selector)=>document.querySelector(selector);
function show(view){ document.querySelectorAll(".view").forEach((node)=>node.classList.toggle("active",node.id===view)); document.querySelectorAll("[data-nav]").forEach((node)=>node.classList.toggle("active",node.dataset.nav===view)); }
function toast(message){ const node=$("#toast"); node.textContent=message; node.classList.add("show"); setTimeout(()=>node.classList.remove("show"),2200); }
function renderLibrary(){ const all=loadCharacters(); $("#character-list").innerHTML=all.length?all.map((c)=>`<button class="character-card" data-id="${c.id}"><span class="avatar">${c.name.slice(0,1).toUpperCase()}</span><span><strong>${c.name}</strong><small>${c.source?.type==="hdc"?"Hero Designer import":"HERO4E character"} &middot; SPD ${c.characteristics.SPD}</small></span><span class="chevron">&rsaquo;</span></button>`).join(""):`<div class="empty"><strong>No characters yet</strong><p>Your roster is stored locally on this device.</p></div>`; document.querySelectorAll("[data-id]").forEach((node)=>node.addEventListener("click",()=>openCharacter(node.dataset.id))); }
function inputStat(key,value){ return `<label class="stat"><span>${key}</span><input inputmode="numeric" data-stat="${key}" value="${value}" aria-label="${key}" /></label>`; }
function escapeHtml(value){ const node=document.createElement("span"); node.textContent=String(value??""); return node.innerHTML; }
function renderEntries(){ const labels={skills:"Skills",perks:"Perks",talents:"Talents",martialarts:"Martial Arts",powers:"Powers",disadvantages:"Disadvantages",equipment:"Equipment"}; const groups=Object.entries(current.sections||{}).filter(([,entries])=>entries.length); const total=groups.reduce((sum,[,entries])=>sum+entries.length,0); $("#abilities-panel").hidden=!total; $("#ability-count").textContent=total?`${total} imported entries`:""; $("#ability-sections").innerHTML=groups.map(([key,entries])=>`<details ${key==="skills"||key==="powers"?"open":""}><summary>${labels[key]||key} <span>${entries.length}</span></summary><div class="entry-list">${entries.map((entry)=>`<div class="entry"><strong>${escapeHtml(entry.name)}</strong><small>${escapeHtml([entry.alias!==entry.name?entry.alias:"",entry.option,entry.levels?`Levels ${entry.levels}`:""].filter(Boolean).join(" · "))}</small></div>`).join("")}</div></details>`).join(""); $("#export-hdc").hidden=!current.preservedHdc; }
function renderSheet(){ if(!current)return; $("#character-name").textContent=current.name; $("#characteristics").innerHTML=[...primaryKeys,...figuredKeys].map((key)=>inputStat(key,current.characteristics[key])).join(""); $("#resources").innerHTML=["BODY","STUN","END"].map((key)=>`<label><span>${key}</span><input inputmode="numeric" data-current="${key}" value="${current.current[key]}" /><small>/ ${current.characteristics[key]}</small></label>`).join(""); renderDerived(); renderEntries(); const notice=$("#import-notice"); notice.hidden=!current.warnings.length; notice.textContent=current.warnings[0]||""; document.querySelectorAll("[data-stat]").forEach((node)=>node.addEventListener("change",updateStat)); document.querySelectorAll("[data-current]").forEach((node)=>node.addEventListener("change",()=>{current.current[node.dataset.current]=Number(node.value)})); }
function renderDerived(){ const c=current.characteristics; $("#characteristic-cost").textContent=`${characteristicCost(c)} primary points`; $("#combat-values").innerHTML=[["OCV",combatValue(c.DEX)],["DCV",combatValue(c.DEX)],["ECV",combatValue(c.EGO)],["DEX roll",`${9+Math.floor(c.DEX/5+0.5)}-`],["EGO roll",`${9+Math.floor(c.EGO/5+0.5)}-`]].map(([k,v])=>`<div class="stat read"><span>${k}</span><strong>${v}</strong></div>`).join(""); }
function updateStat(event){ const key=event.target.dataset.stat; current.characteristics[key]=Number(event.target.value); if(primaryKeys.includes(key)){ const bases=figured(current.characteristics); for(const figuredKey of figuredKeys){ current.characteristics[figuredKey]=bases[figuredKey]; const input=document.querySelector(`[data-stat="${figuredKey}"]`); if(input)input.value=bases[figuredKey]; } } renderDerived(); }
function openCharacter(id){ current=getCharacter(id); renderSheet(); show("sheet-view"); }
function createCharacter(){ current=normalizeCharacter({name:"New Hero"}); saveCharacter(current); renderLibrary(); renderSheet(); show("sheet-view"); }
async function exportHdc(){ if(!current?.preservedHdc){toast("This character has no preserved HDC source");return;} const filename=`${current.name.replace(/[\/:*?"<>|]/g,"-")}.hdc`; const file=new File([current.preservedHdc],filename,{type:"application/xml"}); try{ if(navigator.canShare?.({files:[file]})){ await navigator.share({title:`${current.name} HDC`,files:[file]}); toast("HDC shared"); return; } }catch(error){ if(error.name==="AbortError")return; console.warn(error); } const url=URL.createObjectURL(file); const link=document.createElement("a"); link.href=url; link.download=filename; document.body.append(link); link.click(); link.remove(); setTimeout(()=>URL.revokeObjectURL(url),1000); toast("HDC downloaded"); }
$("#export-hdc").addEventListener("click",exportHdc);
$("#new-character").addEventListener("click",createCharacter); $("#back-button").addEventListener("click",()=>{renderLibrary();show("library-view")}); $("#save-button").addEventListener("click",()=>{ current.updatedAt=new Date().toISOString(); saveCharacter(current); toast("Character saved on this device"); renderLibrary(); });
$("#hdc-input").addEventListener("change",async(event)=>{ try{ const file=event.target.files[0]; if(!file)return; current=importHdc(await file.text()); saveCharacter(current); renderLibrary(); renderSheet(); show("sheet-view"); toast(`${current.name} imported`); }catch(error){toast(error.message)} finally{event.target.value="";} });
$("#sample-character").addEventListener("click",async(event)=>{ const button=event.currentTarget; button.disabled=true; button.textContent="Importing..."; toast("Loading Iron Wolf HDC..."); try{ const response=await fetch("./samples/The%20Iron%20Wolf.hdc",{cache:"no-store"}); if(!response.ok)throw new Error(`Sample download failed (${response.status})`); current=importHdc(await response.text()); saveCharacter(current); renderLibrary(); renderSheet(); show("sheet-view"); toast("The Iron Wolf imported successfully"); }catch(error){ console.error(error); toast(`Import failed: ${error.message}`); }finally{ button.disabled=false; button.textContent="Import Iron Wolf sample"; } });
document.querySelectorAll("[data-roll]").forEach((button)=>button.addEventListener("click",()=>{ const type=button.dataset.roll; const result=type==="3d6"?roll3d6():type==="normal"?rollNormalDamage():rollKillingDamage(); $("#roll-result").innerHTML=type==="3d6"?`<strong>${result.total}</strong><span>${result.dice.join(" + ")}</span>`:`<strong>${result.stun} STUN &middot; ${result.body} BODY</strong><span>${result.dice.join(" + ")}${result.multiplier?` &middot; &times;${result.multiplier}`:""}</span>`; }));
document.querySelectorAll("[data-nav]").forEach((button)=>button.addEventListener("click",()=>{ if(button.dataset.nav==="sheet-view"&&!current){toast("Choose or create a character first");return;} show(button.dataset.nav); }));
window.addEventListener("beforeinstallprompt",(event)=>{event.preventDefault();installPrompt=event;$("#install-button").hidden=false}); $("#install-button").addEventListener("click",async()=>{await installPrompt?.prompt();installPrompt=null;$("#install-button").hidden=true});
$("#refresh-button").addEventListener("click",async(event)=>{ const button=event.currentTarget; button.disabled=true; button.textContent="Refreshing..."; toast("Updating HERO4E Mobile..."); try{ const registrations=await navigator.serviceWorker?.getRegistrations?.()||[]; await Promise.all(registrations.map((registration)=>registration.update())); const cacheKeys=await caches?.keys?.()||[]; await Promise.all(cacheKeys.filter((key)=>key.startsWith("hero4e-mobile-")).map((key)=>caches.delete(key))); const url=new URL(location.href); url.searchParams.set("refresh",Date.now()); location.replace(url); }catch(error){ console.error(error); button.disabled=false; button.textContent="Refresh app"; toast(`Refresh failed: ${error.message}`); } });
if("serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js"); renderLibrary();

