import { characteristicCost, combatValue, figured, normalizeCharacter, primaryKeys, figuredKeys, roll3d6, rollNormalDamage, rollKillingDamage } from "./rules.js";
import { importHdc } from "./hdc.js";
import { getCharacter, loadCharacters, saveCharacter } from "./store.js";
let current=null; let installPrompt=null;
const $=(selector)=>document.querySelector(selector);
function show(view){ document.querySelectorAll(".view").forEach((node)=>node.classList.toggle("active",node.id===view)); document.querySelectorAll("[data-nav]").forEach((node)=>node.classList.toggle("active",node.dataset.nav===view)); }
function toast(message){ const node=$("#toast"); node.textContent=message; node.classList.add("show"); setTimeout(()=>node.classList.remove("show"),2200); }
function renderLibrary(){ const all=loadCharacters(); $("#character-list").innerHTML=all.length?all.map((c)=>`<button class="character-card" data-id="${c.id}"><span class="avatar">${c.name.slice(0,1).toUpperCase()}</span><span><strong>${c.name}</strong><small>${c.source?.type==="hdc"?"Hero Designer import":"HERO4E character"} Â· SPD ${c.characteristics.SPD}</small></span><span class="chevron">â€º</span></button>`).join(""):`<div class="empty"><strong>No characters yet</strong><p>Your roster is stored locally on this device.</p></div>`; document.querySelectorAll("[data-id]").forEach((node)=>node.addEventListener("click",()=>openCharacter(node.dataset.id))); }
function inputStat(key,value){ return `<label class="stat"><span>${key}</span><input inputmode="numeric" data-stat="${key}" value="${value}" aria-label="${key}" /></label>`; }
function renderSheet(){ if(!current)return; $("#character-name").textContent=current.name; $("#characteristics").innerHTML=[...primaryKeys,...figuredKeys].map((key)=>inputStat(key,current.characteristics[key])).join(""); $("#resources").innerHTML=["BODY","STUN","END"].map((key)=>`<label><span>${key}</span><input inputmode="numeric" data-current="${key}" value="${current.current[key]}" /><small>/ ${current.characteristics[key]}</small></label>`).join(""); renderDerived(); const notice=$("#import-notice"); notice.hidden=!current.warnings.length; notice.textContent=current.warnings[0]||""; document.querySelectorAll("[data-stat]").forEach((node)=>node.addEventListener("change",updateStat)); document.querySelectorAll("[data-current]").forEach((node)=>node.addEventListener("change",()=>{current.current[node.dataset.current]=Number(node.value)})); }
function renderDerived(){ const c=current.characteristics; $("#characteristic-cost").textContent=`${characteristicCost(c)} primary points`; $("#combat-values").innerHTML=[["OCV",combatValue(c.DEX)],["DCV",combatValue(c.DEX)],["ECV",combatValue(c.EGO)],["DEX roll",`${9+Math.floor(c.DEX/5+0.5)}-`],["EGO roll",`${9+Math.floor(c.EGO/5+0.5)}-`]].map(([k,v])=>`<div class="stat read"><span>${k}</span><strong>${v}</strong></div>`).join(""); }
function updateStat(event){ const key=event.target.dataset.stat; current.characteristics[key]=Number(event.target.value); if(primaryKeys.includes(key)){ const bases=figured(current.characteristics); for(const figuredKey of figuredKeys){ current.characteristics[figuredKey]=bases[figuredKey]; const input=document.querySelector(`[data-stat="${figuredKey}"]`); if(input)input.value=bases[figuredKey]; } } renderDerived(); }
function openCharacter(id){ current=getCharacter(id); renderSheet(); show("sheet-view"); }
function createCharacter(){ current=normalizeCharacter({name:"New Hero"}); saveCharacter(current); renderLibrary(); renderSheet(); show("sheet-view"); }
$("#new-character").addEventListener("click",createCharacter); $("#back-button").addEventListener("click",()=>{renderLibrary();show("library-view")}); $("#save-button").addEventListener("click",()=>{ current.updatedAt=new Date().toISOString(); saveCharacter(current); toast("Character saved on this device"); renderLibrary(); });
$("#hdc-input").addEventListener("change",async(event)=>{ try{ const file=event.target.files[0]; if(!file)return; current=importHdc(await file.text()); saveCharacter(current); renderLibrary(); renderSheet(); show("sheet-view"); toast(`${current.name} imported`); }catch(error){toast(error.message)} finally{event.target.value="";} });
$("#sample-character").addEventListener("click",async()=>{ try{ const response=await fetch("./samples/The%20Iron%20Wolf.hdc"); if(!response.ok)throw new Error("Sample download failed"); current=importHdc(await response.text()); saveCharacter(current); renderLibrary(); renderSheet(); show("sheet-view"); toast("The Iron Wolf imported"); }catch(error){toast(error.message)} });
document.querySelectorAll("[data-roll]").forEach((button)=>button.addEventListener("click",()=>{ const type=button.dataset.roll; const result=type==="3d6"?roll3d6():type==="normal"?rollNormalDamage():rollKillingDamage(); $("#roll-result").innerHTML=type==="3d6"?`<strong>${result.total}</strong><span>${result.dice.join(" + ")}</span>`:`<strong>${result.stun} STUN Â· ${result.body} BODY</strong><span>${result.dice.join(" + ")}${result.multiplier?` Â· Ã—${result.multiplier}`:""}</span>`; }));
document.querySelectorAll("[data-nav]").forEach((button)=>button.addEventListener("click",()=>{ if(button.dataset.nav==="sheet-view"&&!current){toast("Choose or create a character first");return;} show(button.dataset.nav); }));
window.addEventListener("beforeinstallprompt",(event)=>{event.preventDefault();installPrompt=event;$("#install-button").hidden=false}); $("#install-button").addEventListener("click",async()=>{await installPrompt?.prompt();installPrompt=null;$("#install-button").hidden=true});
if("serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js"); renderLibrary();

