import { characteristicCost, combatValue, figured, normalizeCharacter, primaryKeys, figuredKeys, roll3d6, rollNormalDamage, rollKillingDamage } from "./rules.js";
import { importHdc, exportHdc as buildHdc } from "./hdc.js";
import { getCharacter, loadCharacters, saveCharacter } from "./store.js";
import { exportCharacterJson, importCharacterJson } from "./interchange.js";
let current=null; let installPrompt=null;
const $=(selector)=>document.querySelector(selector);
function show(view){ document.querySelectorAll(".view").forEach((node)=>node.classList.toggle("active",node.id===view)); document.querySelectorAll("[data-nav]").forEach((node)=>node.classList.toggle("active",node.dataset.nav===view)); }
function toast(message){ const node=$("#toast"); node.textContent=message; node.classList.add("show"); setTimeout(()=>node.classList.remove("show"),2200); }
function renderLibrary(){ const all=loadCharacters(); $("#character-list").innerHTML=all.length?all.map((c)=>`<button class="character-card" data-id="${c.id}"><span class="avatar">${c.name.slice(0,1).toUpperCase()}</span><span><strong>${c.name}</strong><small>${c.source?.type==="hdc"?"Hero Designer import":"HERO4E character"} &middot; SPD ${c.characteristics.SPD}</small></span><span class="chevron">&rsaquo;</span></button>`).join(""):`<div class="empty"><strong>No characters yet</strong><p>Your roster is stored locally on this device.</p></div>`; document.querySelectorAll("[data-id]").forEach((node)=>node.addEventListener("click",()=>openCharacter(node.dataset.id))); }
function inputStat(key,value){ return `<label class="stat"><span>${key}</span><input inputmode="numeric" data-stat="${key}" value="${value}" aria-label="${key}" /></label>`; }
function escapeHtml(value){ const node=document.createElement("span"); node.textContent=String(value??""); return node.innerHTML; }
function markHdcDirty(){ if(current?.preservedHdc) current.hdcDirty=true; }
function sectionLabels(){return {skills:"Skills",perks:"Perks",talents:"Talents",martialarts:"Martial Arts",powers:"Powers",disadvantages:"Disadvantages",equipment:"Equipment"};}
function renderEntries(){ const labels=sectionLabels(); const groups=Object.entries(current.sections||{}).filter(([,entries])=>entries.length); const total=groups.reduce((sum,[,entries])=>sum+entries.length,0); $("#abilities-panel").hidden=!total&&Boolean(current.preservedHdc); $("#ability-count").textContent=total?`${total} ${current.preservedHdc?"imported ":""}entries`:"No abilities yet"; $("#ability-sections").innerHTML=groups.map(([key,entries])=>`<details ${key==="skills"||key==="powers"?"open":""}><summary>${labels[key]||key} <span>${entries.length}</span></summary><div class="entry-list">${entries.map((entry)=>`<button class="entry" data-entry-section="${key}" data-entry-id="${escapeHtml(entry.id)}"><strong>${escapeHtml(entry.name)}</strong><small>${escapeHtml([entry.alias!==entry.name?entry.alias:"",entry.option,entry.levels?`Levels ${entry.levels}`:""].filter(Boolean).join(" · "))}</small></button>`).join("")}</div></details>`).join(""); document.querySelectorAll("[data-entry-id]").forEach((node)=>node.addEventListener("click",()=>openEntryEditor(node.dataset.entrySection,node.dataset.entryId))); $("#export-hdc").hidden=!current.preservedHdc; $("#add-entry").hidden=Boolean(current.preservedHdc); }
function renderSheet(){ if(!current)return; $("#character-name").textContent=current.name; $("#player-name").textContent=current.playerName?`Player: ${current.playerName}`:"Tap to edit identity"; $("#characteristics").innerHTML=[...primaryKeys,...figuredKeys].map((key)=>inputStat(key,current.characteristics[key])).join(""); $("#resources").innerHTML=["BODY","STUN","END"].map((key)=>`<label><span>${key}</span><input inputmode="numeric" data-current="${key}" value="${current.current[key]}" /><small>/ ${current.characteristics[key]}</small></label>`).join(""); renderDerived(); renderEntries(); const notice=$("#import-notice"); notice.hidden=!current.warnings.length; notice.textContent=current.warnings[0]||""; document.querySelectorAll("[data-stat]").forEach((node)=>node.addEventListener("change",updateStat)); document.querySelectorAll("[data-current]").forEach((node)=>node.addEventListener("change",()=>{current.current[node.dataset.current]=Number(node.value)})); }
function renderDerived(){ const c=current.characteristics; $("#characteristic-cost").textContent=`${characteristicCost(c)} primary points`; $("#combat-values").innerHTML=[["OCV",combatValue(c.DEX)],["DCV",combatValue(c.DEX)],["ECV",combatValue(c.EGO)],["DEX roll",`${9+Math.floor(c.DEX/5+0.5)}-`],["EGO roll",`${9+Math.floor(c.EGO/5+0.5)}-`]].map(([k,v])=>`<div class="stat read"><span>${k}</span><strong>${v}</strong></div>`).join(""); }
function updateStat(event){ markHdcDirty(); const key=event.target.dataset.stat; const previous=Number(current.characteristics[key]); const oldBases=figured(current.characteristics); current.characteristics[key]=Number(event.target.value); if(primaryKeys.includes(key)){ const newBases=figured(current.characteristics); for(const figuredKey of figuredKeys){ current.characteristics[figuredKey]+=newBases[figuredKey]-oldBases[figuredKey]; const input=document.querySelector(`[data-stat="${figuredKey}"]`); if(input)input.value=current.characteristics[figuredKey]; } } if(!Number.isFinite(current.characteristics[key]))current.characteristics[key]=previous; renderDerived(); }
function openCharacter(id){ current=getCharacter(id); renderSheet(); show("sheet-view"); }
function createCharacter(){ current=normalizeCharacter({name:"New Hero"}); saveCharacter(current); renderLibrary(); renderSheet(); show("sheet-view"); }
function downloadFile(text,filename,type){ const file=new File([text],filename,{type}); const url=URL.createObjectURL(file); const link=document.createElement("a"); link.href=url; link.download=filename; document.body.append(link); link.click(); link.remove(); setTimeout(()=>URL.revokeObjectURL(url),1000); return file; }
async function exportJson(){ const filename=`${current.name.replace(/[\/:*?"<>|]/g,"-")}.hero4e`; const text=exportCharacterJson(current); const file=new File([text],filename,{type:"application/json"}); try{if(navigator.canShare?.({files:[file]})){await navigator.share({title:`${current.name} HERO4E`,files:[file]});return;}}catch(error){if(error.name==="AbortError")return;} downloadFile(text,filename,"application/json"); toast("HERO4E character downloaded");}
async function exportHdc(){ if(!current?.preservedHdc){toast("This character has no preserved HDC source");return;} const hdcText=buildHdc(current); const filename=`${current.name.replace(/[\/:*?"<>|]/g,"-")}.hdc`; const file=new File([hdcText],filename,{type:"application/xml"}); try{ if(navigator.canShare?.({files:[file]})){ await navigator.share({title:`${current.name} HDC`,files:[file]}); toast("HDC shared"); return; } }catch(error){ if(error.name==="AbortError")return; console.warn(error); } const url=URL.createObjectURL(file); const link=document.createElement("a"); link.href=url; link.download=filename; document.body.append(link); link.click(); link.remove(); setTimeout(()=>URL.revokeObjectURL(url),1000); toast("HDC downloaded"); }
function openEntryEditor(section,id){
  const entry=(current.sections?.[section]||[]).find((item)=>String(item.id)===String(id)); if(!entry)return;
  $("#entry-dialog").dataset.mode="edit"; $("#entry-section-label").hidden=true; $("#entry-organize").hidden=false; $("#entry-section").value=section; $("#entry-id").value=id; $("#entry-name").value=entry.name||""; $("#entry-levels").value=entry.levels||0; $("#entry-notes").value=entry.notes||""; $("#entry-dialog").showModal();
}
$("#entry-form").addEventListener("submit",(event)=>{ event.preventDefault(); let section=$("#entry-section").value; let entry=(current.sections?.[section]||[]).find((item)=>String(item.id)===String($("#entry-id").value)); if($("#entry-dialog").dataset.mode==="new"){section=$("#entry-new-section").value; current.sections[section]??=[]; entry={id:crypto.randomUUID(),tag:"CANONICAL",name:"",alias:"",option:"",levels:0,baseCost:0,notes:"",rawXml:""}; current.sections[section].push(entry);} if(!entry)return; entry.name=$("#entry-name").value.trim()||entry.name; entry.levels=Number($("#entry-levels").value||0); entry.notes=$("#entry-notes").value; markHdcDirty(); $("#entry-dialog").close(); renderEntries(); toast("Ability updated — save the character"); });
function moveEntry(delta){const section=$("#entry-section").value,entries=current.sections?.[section]||[],index=entries.findIndex(e=>String(e.id)===String($("#entry-id").value)),target=index+delta;if(index<0||target<0||target>=entries.length)return;[entries[index],entries[target]]=[entries[target],entries[index]];markHdcDirty();$("#entry-dialog").close();renderEntries();toast("Ability order updated");}
$("#move-entry-up").addEventListener("click",()=>moveEntry(-1)); $("#move-entry-down").addEventListener("click",()=>moveEntry(1));
$("#delete-entry").addEventListener("click",()=>{const section=$("#entry-section").value;current.sections[section]=(current.sections?.[section]||[]).filter(e=>String(e.id)!==String($("#entry-id").value));markHdcDirty();$("#entry-dialog").close();renderEntries();toast("Ability removed — export creates updated HDC");});
$("#add-entry").addEventListener("click",()=>{$("#entry-dialog").dataset.mode="new";$("#entry-section-label").hidden=false;$("#entry-organize").hidden=true;$("#entry-section").value="";$("#entry-id").value="";$("#entry-name").value="";$("#entry-levels").value=0;$("#entry-notes").value="";$("#entry-dialog").showModal();});
$("#cancel-entry").addEventListener("click",()=>$("#entry-dialog").close());
$("#export-json").addEventListener("click",exportJson); $("#export-hdc").addEventListener("click",exportHdc);
$("#identity-button").addEventListener("click",()=>{$("#identity-name").value=current.name;$("#identity-player").value=current.playerName||"";$("#identity-dialog").showModal();});
$("#identity-form").addEventListener("submit",event=>{event.preventDefault();current.name=$("#identity-name").value.trim()||current.name;current.playerName=$("#identity-player").value.trim();markHdcDirty();$("#identity-dialog").close();renderSheet();toast("Identity updated — save the character");}); $("#cancel-identity").addEventListener("click",()=>$("#identity-dialog").close());
$("#new-character").addEventListener("click",createCharacter); $("#back-button").addEventListener("click",()=>{renderLibrary();show("library-view")}); $("#save-button").addEventListener("click",()=>{ current.updatedAt=new Date().toISOString(); saveCharacter(current); toast("Character saved on this device"); renderLibrary(); });
$("#json-input").addEventListener("change",async(event)=>{try{const file=event.target.files[0];if(!file)return;current=importCharacterJson(await file.text());saveCharacter(current);renderLibrary();renderSheet();show("sheet-view");toast(`${current.name} imported`);}catch(error){toast(error.message)}finally{event.target.value="";}});
$("#hdc-input").addEventListener("change",async(event)=>{ try{ const file=event.target.files[0]; if(!file)return; current=importHdc(await file.text()); saveCharacter(current); renderLibrary(); renderSheet(); show("sheet-view"); toast(`${current.name} imported`); }catch(error){toast(error.message)} finally{event.target.value="";} });
$("#sample-character").addEventListener("click",async(event)=>{ const button=event.currentTarget; button.disabled=true; button.textContent="Importing..."; toast("Loading Iron Wolf HDC..."); try{ const response=await fetch("./samples/The%20Iron%20Wolf.hdc",{cache:"no-store"}); if(!response.ok)throw new Error(`Sample download failed (${response.status})`); current=importHdc(await response.text()); saveCharacter(current); renderLibrary(); renderSheet(); show("sheet-view"); toast("The Iron Wolf imported successfully"); }catch(error){ console.error(error); toast(`Import failed: ${error.message}`); }finally{ button.disabled=false; button.textContent="Import Iron Wolf sample"; } });
document.querySelectorAll("[data-roll]").forEach((button)=>button.addEventListener("click",()=>{ const type=button.dataset.roll; const result=type==="3d6"?roll3d6():type==="normal"?rollNormalDamage():rollKillingDamage(); $("#roll-result").innerHTML=type==="3d6"?`<strong>${result.total}</strong><span>${result.dice.join(" + ")}</span>`:`<strong>${result.stun} STUN &middot; ${result.body} BODY</strong><span>${result.dice.join(" + ")}${result.multiplier?` &middot; &times;${result.multiplier}`:""}</span>`; }));
document.querySelectorAll("[data-nav]").forEach((button)=>button.addEventListener("click",()=>{ if(button.dataset.nav==="sheet-view"&&!current){toast("Choose or create a character first");return;} show(button.dataset.nav); }));
window.addEventListener("beforeinstallprompt",(event)=>{event.preventDefault();installPrompt=event;$("#install-button").hidden=false}); $("#install-button").addEventListener("click",async()=>{await installPrompt?.prompt();installPrompt=null;$("#install-button").hidden=true});
$("#refresh-button").addEventListener("click",async(event)=>{ const button=event.currentTarget; button.disabled=true; button.textContent="Refreshing..."; toast("Updating HERO4E Mobile..."); try{ const registrations=await navigator.serviceWorker?.getRegistrations?.()||[]; await Promise.all(registrations.map((registration)=>registration.update())); const cacheKeys=await caches?.keys?.()||[]; await Promise.all(cacheKeys.filter((key)=>key.startsWith("hero4e-mobile-")).map((key)=>caches.delete(key))); const url=new URL(location.href); url.searchParams.set("refresh",Date.now()); location.replace(url); }catch(error){ console.error(error); button.disabled=false; button.textContent="Refresh app"; toast(`Refresh failed: ${error.message}`); } });
if("serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js"); renderLibrary();

