export const SPEED_PHASES_4E=Object.freeze([[],[12],[6,12],[4,8,12],[3,6,9,12],[3,5,8,10,12],[2,4,6,8,10,12],[2,4,6,7,9,11,12],[2,3,5,6,8,9,11,12],[2,3,4,6,7,8,10,11,12],[2,3,4,5,6,8,9,10,11,12],[2,3,4,5,6,7,8,9,10,11,12],[1,2,3,4,5,6,7,8,9,10,11,12]].map(Object.freeze));
export function speedPhases(speed){const value=Math.min(12,Math.max(0,Math.floor(Number(speed)||0)));return SPEED_PHASES_4E[value];}
export function hasPhase(speed,segment){return Number.isInteger(Number(segment))&&speedPhases(speed).includes(Number(segment));}
export function advanceSegment(combat,delta=1){let segment=Number(combat?.segment||12),turn=Math.max(1,Number(combat?.turn||1));if(delta>=0){for(let i=0;i<delta;i++){if(segment===12){segment=1;turn++;}else segment++;}}else for(let i=0;i>delta;i--){if(segment===1){segment=12;turn=Math.max(1,turn-1);}else segment--;}return {segment,turn};}
export function recoverResources({stun,end,stunMax,endMax,rec}){const recovery=Math.max(0,Number(rec)||0),oldStun=Number(stun),oldEnd=Number(end);let newStun=oldStun+recovery,newEnd=Math.max(0,oldEnd)+recovery;if(newStun>stunMax)newStun=Math.max(stunMax,oldStun);if(newEnd>endMax)newEnd=Math.max(endMax,oldEnd);const wakesUp=oldStun<=0&&newStun>0;if(wakesUp)newEnd=Math.min(endMax,newStun);else if(oldStun<=0)newEnd=0;return {STUN:newStun,END:newEnd,stunGained:newStun-oldStun,endGained:Math.max(0,newEnd-oldEnd),wakesUp};}

export const ACTION_TIMING_4E=Object.freeze({attack:{cost:.5,endsPhase:true,label:"Attack"},halfMove:{cost:.5,endsPhase:false,label:"Half Move"},fullMove:{cost:1,endsPhase:false,label:"Full Move"},drawWeapon:{cost:.5,endsPhase:false,label:"Draw Weapon"},brace:{cost:0,endsPhase:false,label:"Brace"},set:{cost:1,endsPhase:false,label:"Set"},recovery:{cost:1,endsPhase:false,label:"Recovery"},hold:{cost:1,endsPhase:true,label:"Hold Action"}});
export function addPhaseAction(state={},actionId){const action=ACTION_TIMING_4E[actionId];if(!action)throw new RangeError(`Unknown Fourth Edition action: ${actionId}`);const used=Number(state.used||0),ended=Boolean(state.ended),log=Array.isArray(state.log)?[...state.log]:[];if(ended)return {...state,legal:false,error:`${action.label} cannot occur after the Phase ended.`};if(action.cost===1&&used>0)return {...state,legal:false,error:`${action.label} requires a full Phase.`};if(used+action.cost>1)return {...state,legal:false,error:`${action.label} exceeds the remaining Phase.`};log.push(actionId);return {used:used+action.cost,ended:action.endsPhase||used+action.cost>=1,held:actionId==="hold",log,legal:true,error:null};}
export function clearPhaseActions(){return {used:0,ended:false,held:false,log:[],legal:true,error:null};}
export function applyDefenses4e(damage,{defense=0,resistantDefense=0}={}){const stun=Number(damage?.stun),body=Number(damage?.body),total=Math.max(0,Number(defense)),resistant=Math.max(0,Number(resistantDefense));if(![stun,body,total,resistant].every(Number.isFinite))throw new TypeError("Fourth Edition damage and defenses must be numeric.");if(damage.type==="normal")return {stun:Math.max(0,stun-total),body:Math.max(0,body-total)};if(damage.type!=="killing")throw new RangeError("Unknown Fourth Edition damage type: "+damage.type);const bodyTaken=Math.max(0,body-resistant);return {stun:Math.max(bodyTaken,stun-total),body:bodyTaken};}
export function applyDamage4e(current,damage,defenses,constitution=10){const taken=applyDefenses4e(damage,defenses),next={BODY:Number(current.BODY)-taken.body,STUN:Number(current.STUN)-taken.stun,END:Number(current.END)},statuses={stunned:taken.stun>=Number(constitution),unconscious:Number(current.STUN)-taken.stun<=0,dead:Number(current.BODY)-taken.body<=-Math.abs(Number(current.BODY))};return {current:next,taken,statuses};}
