export const SPEED_PHASES_4E=Object.freeze([[],[12],[6,12],[4,8,12],[3,6,9,12],[3,5,8,10,12],[2,4,6,8,10,12],[2,4,6,7,9,11,12],[2,3,5,6,8,9,11,12],[2,3,4,6,7,8,10,11,12],[2,3,4,5,6,8,9,10,11,12],[2,3,4,5,6,7,8,9,10,11,12],[1,2,3,4,5,6,7,8,9,10,11,12]].map(Object.freeze));
export function speedPhases(speed){const value=Math.min(12,Math.max(0,Math.floor(Number(speed)||0)));return SPEED_PHASES_4E[value];}
export function hasPhase(speed,segment){return Number.isInteger(Number(segment))&&speedPhases(speed).includes(Number(segment));}
export function advanceSegment(combat,delta=1){let segment=Number(combat?.segment||12),turn=Math.max(1,Number(combat?.turn||1));if(delta>=0){for(let i=0;i<delta;i++){if(segment===12){segment=1;turn++;}else segment++;}}else for(let i=0;i>delta;i--){if(segment===1){segment=12;turn=Math.max(1,turn-1);}else segment--;}return {segment,turn};}
export function recoverResources({stun,end,stunMax,endMax,rec}){const recovery=Math.max(0,Number(rec)||0),oldStun=Number(stun),oldEnd=Number(end);let newStun=oldStun+recovery,newEnd=Math.max(0,oldEnd)+recovery;if(newStun>stunMax)newStun=Math.max(stunMax,oldStun);if(newEnd>endMax)newEnd=Math.max(endMax,oldEnd);const wakesUp=oldStun<=0&&newStun>0;if(wakesUp)newEnd=Math.min(endMax,newStun);else if(oldStun<=0)newEnd=0;return {STUN:newStun,END:newEnd,stunGained:newStun-oldStun,endGained:Math.max(0,newEnd-oldEnd),wakesUp};}

export const ACTION_TIMING_4E=Object.freeze({attack:{cost:.5,endsPhase:true,label:"Attack"},halfMove:{cost:.5,endsPhase:false,label:"Half Move"},fullMove:{cost:1,endsPhase:false,label:"Full Move"},drawWeapon:{cost:.5,endsPhase:false,label:"Draw Weapon"},brace:{cost:0,endsPhase:false,label:"Brace"},set:{cost:1,endsPhase:false,label:"Set"},recovery:{cost:1,endsPhase:false,label:"Recovery"},hold:{cost:1,endsPhase:true,label:"Hold Action"}});
export function addPhaseAction(state={},actionId){const action=ACTION_TIMING_4E[actionId];if(!action)throw new RangeError(`Unknown Fourth Edition action: ${actionId}`);const used=Number(state.used||0),ended=Boolean(state.ended),log=Array.isArray(state.log)?[...state.log]:[];if(ended)return {...state,legal:false,error:`${action.label} cannot occur after the Phase ended.`};if(action.cost===1&&used>0)return {...state,legal:false,error:`${action.label} requires a full Phase.`};if(used+action.cost>1)return {...state,legal:false,error:`${action.label} exceeds the remaining Phase.`};log.push(actionId);return {used:used+action.cost,ended:action.endsPhase||used+action.cost>=1,held:actionId==="hold",log,legal:true,error:null};}
export function clearPhaseActions(){return {used:0,ended:false,held:false,log:[],legal:true,error:null};}
export function applyDefenses4e(damage,{defense=0,resistantDefense=0}={}){const stun=Number(damage?.stun),body=Number(damage?.body),total=Math.max(0,Number(defense)),resistant=Math.max(0,Number(resistantDefense));if(![stun,body,total,resistant].every(Number.isFinite))throw new TypeError("Fourth Edition damage and defenses must be numeric.");if(damage.type==="normal")return {stun:Math.max(0,stun-total),body:Math.max(0,body-total)};if(damage.type!=="killing")throw new RangeError("Unknown Fourth Edition damage type: "+damage.type);const bodyTaken=Math.max(0,body-resistant);return {stun:Math.max(bodyTaken,stun-total),body:bodyTaken};}
export function applyDamage4e(current,damage,defenses,constitution=10){const taken=applyDefenses4e(damage,defenses),next={BODY:Number(current.BODY)-taken.body,STUN:Number(current.STUN)-taken.stun,END:Number(current.END)},statuses={stunned:taken.stun>=Number(constitution),unconscious:Number(current.STUN)-taken.stun<=0,dead:Number(current.BODY)-taken.body<=-Math.abs(Number(current.BODY))};return {current:next,taken,statuses};}

export const HIT_LOCATIONS_4E=Object.freeze([
 {min:3,max:5,name:"Head",stunX:5,nStun:2,bodyX:2,toHit:-8},
 {min:6,max:6,name:"Hands",stunX:1,nStun:.5,bodyX:.5,toHit:-6},
 {min:7,max:8,name:"Arms",stunX:2,nStun:.5,bodyX:.5,toHit:-5},
 {min:9,max:9,name:"Shoulders",stunX:3,nStun:1,bodyX:1,toHit:-5},
 {min:10,max:11,name:"Chest",stunX:3,nStun:1,bodyX:1,toHit:-3},
 {min:12,max:12,name:"Stomach",stunX:4,nStun:1.5,bodyX:1,toHit:-7},
 {min:13,max:13,name:"Vitals",stunX:4,nStun:1.5,bodyX:2,toHit:-8},
 {min:14,max:14,name:"Thighs",stunX:2,nStun:1,bodyX:1,toHit:-4},
 {min:15,max:16,name:"Legs",stunX:2,nStun:.5,bodyX:.5,toHit:-6},
 {min:17,max:18,name:"Feet",stunX:1,nStun:.5,bodyX:.5,toHit:-8},
].map(Object.freeze));
export function hitLocation4e(total){const roll=Number(total);if(!Number.isInteger(roll)||roll<3||roll>18)throw new RangeError("Hit Location requires a 3d6 total from 3 through 18.");return HIT_LOCATIONS_4E.find(location=>roll>=location.min&&roll<=location.max);}
export function knockback4e(body,{dice=[1,1],resistance=0,impact="ground"}={}){const bodyDone=Math.max(0,Number(body)||0),rolled=Array.isArray(dice)?dice.reduce((sum,value)=>sum+Number(value||0),0):Number(dice)||0,raw=bodyDone-rolled,distance=Math.max(0,raw-Math.max(0,Number(resistance)||0));return {body:bodyDone,roll:rolled,raw,distance,knockedDown:raw===0||distance>0,result:raw<0?"No Knockback":distance>0?`${distance}\" Knockback`:"Knocked down",impactDice:impact==="wall"?distance:Math.floor(distance/2),reference:"BBB p. 166"};}
export function presenceAttack4e(pre,{roll=0,modifierDice=0,targetPre=10,targetEgo=10}={}){const dice=Math.max(0,Math.floor(Number(pre||0)/5)+Number(modifierDice||0)),total=Number(roll)||0,defense=Math.max(Number(targetPre)||0,Number(targetEgo)||0),margin=total-defense;let level=0,effect="No listed effect";if(margin>=30){level=4;effect="Cowed";}else if(margin>=20){level=3;effect="Awed";}else if(margin>=10){level=2;effect="Very impressed";}else if(margin>=0){level=1;effect="Impressed";}return {dice,total,defense,margin,level,effect,reference:"BBB p. 170"};}
