import { combatValue, rollHeroDice } from "./rules.js";
import { attackPowerProfile4e, powerDamageDice4e } from "./dice.js";

const escapeHtml=value=>{const node=document.createElement("span");node.textContent=String(value??"");return node.innerHTML;};
export function createDiceTray4e({getCharacter,root=document}={}){
  const $=selector=>root.querySelector(selector),$$=selector=>[...root.querySelectorAll(selector)];
  let count=3,bodyModifier=0,multiplierModifier=0,rollModifier=0,queued=null;
  const multiplierFormula=()=>{const adjustment=-1+multiplierModifier;return `1d6${adjustment===0?"":adjustment>0?`+${adjustment}`:`−${Math.abs(adjustment)}`}`;};
  const dialog=$("#dice-dialog"),open=()=>{if(!dialog.open)dialog.showModal();};
  const mode=()=>$("[data-dice-mode]:checked")?.dataset.diceMode||"check";
  const setMode=selected=>$$('[data-dice-mode]').forEach(box=>box.checked=box.dataset.diceMode===selected);
  const update=()=>{const selected=mode(),skill=selected==="check",killing=selected==="killing",diceCount=skill?3:count,half=!skill&&$("#dice-half").checked,suffix=half?" + ½d6":"";$("#dice-count-minus").disabled=skill;$("#dice-count-plus").disabled=skill;$("#dice-half").disabled=skill;$$('#killing-adjustments button').forEach(button=>button.disabled=!killing);$("#dice-count-display").textContent=`${diceCount}d6`;$("#roll-dice-tray").textContent=queued?.label?`Roll ${queued.label}`:skill?"Roll Skill Check":`Roll ${diceCount}d6${suffix}`;$("#body-mod-display").textContent=bodyModifier>0?`+${bodyModifier}`:String(bodyModifier);$("#multiplier-mod-display").textContent=multiplierModifier>0?`+${multiplierModifier}`:String(multiplierModifier);$("#roll-mod-display").textContent=rollModifier>0?`+${rollModifier}`:String(rollModifier);$("#multiplier-formula").textContent=multiplierFormula();};
  const diceText=result=>[...result.dice.map(String),...(result.halfDie==null?[]:[`${result.halfDie} (½d6)`])].join(" + ");
  const display=(result,{label=""}={})=>{const dice=diceText(result),prefix=label?`<span>${escapeHtml(label)}</span>`:"",values=result.mode==="check"?`${result.total}`:result.mode==="mental"?`${result.stun} STUN`:`${result.stun} STUN · ${result.body} BODY`,description=result.mode==="check"?dice:result.mode==="mental"?`${dice} · Mental / NND Damage`:result.mode==="normal"?`${dice} · Normal Damage`:`${dice} · STUN Multiplier ×${result.multiplier}`;$("#roll-result").innerHTML=`${prefix}<strong>${values}</strong><span>${description}</span>`;};
  const queue=(config={})=>{queued=config;rollModifier=0;if(config.mode){setMode(config.mode);if(config.count!=null)count=config.count;$("#dice-half").checked=Boolean(config.half);}else setMode("check");$("#roll-result").innerHTML=`<span>Queued</span><strong>${escapeHtml(config.label||"Skill Roll")}</strong><span>${escapeHtml(config.summary||"Adjust the modifier, then tap Roll.")}</span>`;update();open();};
  const roll=()=>{const selected=mode(),result=rollHeroDice({count:selected==="check"?3:count,half:selected!=="check"&&$("#dice-half").checked,mode:selected,bodyModifier,multiplierModifier});if(selected!=="check"){display(result,{label:queued?.label||""});queued=null;update();return;}const adjustedTarget=Number.isFinite(queued?.target)?queued.target+rollModifier:null,adjustedCv=Number.isFinite(queued?.cv)?queued.cv+rollModifier:null;let label=queued?.label||"Skill Roll";if(adjustedTarget!=null)label+=` ${adjustedTarget}− · ${result.total<=adjustedTarget?"SUCCESS":"FAILED"} by ${Math.abs(adjustedTarget-result.total)}`;else if(adjustedCv!=null)label+=` · ${queued.cvLabel||"CV"} ${adjustedCv} · hits ${queued.defenseLabel||"Defense"} ${adjustedCv+11-result.total} or less`;else if(rollModifier)label+=` · modifier ${rollModifier>0?"+":""}${rollModifier}`;display(result,{label});queued=null;update();};
  const rollAgainstTarget=(target,label)=>queue({target:Number(target),label,summary:`Target ${target}−. Adjust the target modifier, then roll.`});
  const queueCombatValue=(cv,label,defenseLabel=label)=>queue({cv:Number(cv),cvLabel:label,defenseLabel,label:`${label} Roll`,summary:`${label} ${cv}. Adjust the modifier, then roll.`});
  const rollPowerAttack=entry=>{const profile=attackPowerProfile4e(entry?.mechanics?.key);if(!profile.attack)return;const cvLabel=profile.mental?"ECV":"OCV",cv=combatValue(getCharacter().characteristics?.[profile.mental?"EGO":"DEX"]);queue({cv,cvLabel,defenseLabel:profile.mental?"ECV":"DCV",label:`${entry.name||entry.mechanics.label} Attack`,summary:`${cvLabel} ${cv}. Adjust the modifier, then roll.`});};
  const rollPowerDamage=entry=>{const profile=powerDamageDice4e(entry);if(!profile)return;queue({...profile,label:`${entry.name||"Power"} Damage`,summary:`${profile.count}d6${profile.half?" + ½d6":""} ${profile.mode} damage.`});};
  const bind=()=>{
    $("#dice-count-minus").addEventListener("click",()=>{count=Math.max(0,count-1);update();});$("#dice-count-plus").addEventListener("click",()=>{count=Math.min(99,count+1);update();});$("#dice-half").addEventListener("change",update);
    $$('[data-dice-mode]').forEach(box=>box.addEventListener("change",()=>{if(!box.checked)box.checked=true;$$('[data-dice-mode]').forEach(other=>{if(other!==box)other.checked=false;});queued=null;update();}));
    $("#roll-mod-minus").addEventListener("click",()=>{rollModifier--;update();});$("#roll-mod-plus").addEventListener("click",()=>{rollModifier++;update();});
    $("#body-mod-minus").addEventListener("click",()=>{bodyModifier--;update();});$("#body-mod-plus").addEventListener("click",()=>{bodyModifier++;update();});$("#multiplier-mod-minus").addEventListener("click",()=>{multiplierModifier--;update();});$("#multiplier-mod-plus").addEventListener("click",()=>{multiplierModifier++;update();});
    $("#roll-dice-tray").addEventListener("click",roll);$("#dice-overlay-button").addEventListener("click",()=>{queued=null;rollModifier=0;setMode("check");$("#roll-result").textContent="Choose a roll.";update();open();});$("#close-dice").addEventListener("click",()=>dialog.close());
    $("#detail-roll-card").addEventListener("click",event=>{const target=Number(event.currentTarget.dataset.target);if(Number.isFinite(target)&&target)rollAgainstTarget(target,event.currentTarget.dataset.label);});update();
  };
  return Object.freeze({bind,open,queue,queueCombatValue,rollAgainstTarget,rollPowerAttack,rollPowerDamage});
}
