export const DISADVANTAGES_4E=Object.freeze({
  accidentalChange:{label:"Accidental Change",options:[{label:"Circumstances",values:{uncommon:5,common:10,veryCommon:15}},{label:"Chance to Change",values:{"8orLess":0,"11orLess":5,"14orLess":10}}]},
  age:{label:"Age",options:[{label:"Age",values:{over40:5,over60:10}}]},
  berserk:{label:"Berserk",options:[{label:"Circumstances",values:{uncommon:5,common:10,veryCommon:15}},{label:"Chance to Go Berserk",values:{"8orLess":0,"11orLess":5,"14orLess":10}},{label:"Chance to Recover",values:{"14orLess":0,"11orLess":5,"8orLess":10}},{label:"Form",values:{berserk:0,enragedOnly:{value:.5,multiply:true}}}]},
  dependence:{label:"Dependence",options:[{label:"Dependent Substance",values:{veryCommon:5,common:10,uncommon:15}},{label:"Time Before Taking Damage",values:{segment:15,phase:10,turn:5,minute:0,fiveMinutes:-5,oneHour:-10,fiveHours:-15}},{label:"Damage",values:{"1d6":0,"2d6":5,"3d6":10}}]},
  dependentNpc:{label:"Dependent NPC",options:[{label:"Competence",values:{incompetent:10,normal:5,slightlyLessPowerful:0,asPowerful:-5}},{label:"Appearance",values:{"8orLess":5,"11orLess":10,"14orLess":15}},{label:"Usefulness",values:{ordinary:0,useful:-5}}]},
  distinctiveFeatures:{label:"Distinctive Features",options:[{label:"Concealability",values:{easilyConcealable:5,concealable:10,notConcealable:15}},{label:"Reaction",values:{noticed:0,major:5,extreme:10}}]},
  hunted:{label:"Hunted or Watched",options:[{label:"Capabilities",values:{lessPowerful:5,asPowerful:10,morePowerful:15}},{label:"Noncombat Influence",values:{ordinary:0,extensiveNci:5}},{label:"Geographical Scope",values:{unlimited:0,limitedArea:-5}},{label:"Appearance",values:{"8orLess":0,"11orLess":5,"14orLess":10}},{label:"Motivation",values:{harshlyPunish:0,mildlyPunish:-5,watchingOnly:{value:.5,multiply:true}}}]},
  normalCharacteristicMaxima:{label:"Normal Characteristic Maxima",fixed:20},
  physicalLimitation:{label:"Physical Limitation",options:[{label:"Frequency",values:{infrequently:5,frequently:10,allTheTime:15}},{label:"Impairment",values:{slightly:0,greatly:5,fully:10}}]},
  psychologicalLimitation:{label:"Psychological Limitation",options:[{label:"Frequency",values:{uncommon:5,common:10,veryCommon:15}},{label:"Intensity",values:{weak:0,strong:5,total:10}}]},
  publicIdentity:{label:"Public Identity",fixed:10},
  reputation:{label:"Reputation",options:[{label:"Recognized",values:{sometimes:5,frequently:10,almostAlways:15}},{label:"Severity",values:{ordinary:0,extreme:5}}]},
  rivalry:{label:"Rivalry",options:[{label:"Situation",values:{professional:5,romantic:5,both:10}},{label:"Position",values:{peer:0,superiorPosition:5}},{label:"Rival",values:{npc:0,playerCharacter:5}}]},
  secretIdentity:{label:"Secret Identity",fixed:15},
  susceptibility:{label:"Susceptibility",options:[{label:"Condition",values:{uncommon:5,common:10,veryCommon:15}},{label:"Take Damage Every",values:{segment:15,phase:10,turn:5,minute:0,fiveMinutes:-5,instant:0}},{label:"Damage",values:{"1d6":0,"2d6":5,"3d6":10}}]},
  unluck:{label:"Unluck",perLevel:5,levelsLabel:"d6"},
  vulnerability:{label:"Vulnerability",options:[{label:"Attack Frequency",values:{uncommon:5,common:10,veryCommon:15}},{label:"Damage Multiple",values:{oneAndOneHalfStun:{value:1,multiply:true},oneAndOneHalfBody:{value:1,multiply:true},doubleStun:{value:2,multiply:true},doubleBody:{value:2,multiply:true}}}]}
});
const pretty=value=>String(value).replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase()).replace(/(\d+)or/g,"$1 or ").replace(/Nci/g,"NCI");
const choiceRule=value=>typeof value==="object"?value:{value,multiply:false};
export function disadvantageOptions4e(key){const d=DISADVANTAGES_4E[key];if(!d)throw new Error("Unknown Fourth Edition disadvantage: "+key);return (d.options||[]).map(group=>({...group,choices:Object.keys(group.values).map(key=>({key,label:pretty(key),value:choiceRule(group.values[key]).value}))}));}
export function normalizeDisadvantageSelections4e(key,selections=[]){let normalized=[...selections];if(key==="psychologicalLimitation"&&normalized[1]==="moderate")normalized[1]="weak";if(key==="hunted"&&normalized.length===3)normalized=[normalized[0],"ordinary","unlimited",normalized[1],normalized[2]];if(key==="reputation"&&normalized.length===1)normalized.push("ordinary");if(key==="rivalry"&&normalized.length===1)normalized.push("peer","npc");if(key==="vulnerability"&&normalized[1])normalized[1]=({halfStun:"oneAndOneHalfStun",halfBody:"oneAndOneHalfBody"}[normalized[1]]||normalized[1]);return normalized;}
const lessRoll=value=>Number(String(value||"").match(/(8|11|14)/)?.[1]);
function disadvantageRolls4e(key,selections){if(key==="psychologicalLimitation")return {roll:{weak:8,strong:11,total:14}[selections[1]],rollLabel:"EGO Roll"};if(key==="accidentalChange")return {roll:lessRoll(selections[1]),rollLabel:"Chance to Change"};if(key==="berserk")return {roll:lessRoll(selections[1]),rollLabel:"Activation Roll",recoveryRoll:lessRoll(selections[2]),recoveryRollLabel:"Recovery Roll"};if(key==="hunted")return {roll:lessRoll(selections[3]),rollLabel:"Appearance Roll"};if(key==="dependentNpc")return {roll:lessRoll(selections[1]),rollLabel:"Appearance Roll"};if(key==="reputation")return {roll:{sometimes:8,frequently:11,almostAlways:14}[selections[0]],rollLabel:"Recognition Roll"};return {};}
export function calculateDisadvantage4e(key,{levels=1,selections=[]}={}){selections=normalizeDisadvantageSelections4e(key,selections);const d=DISADVANTAGES_4E[key];if(!d)throw new Error("Unknown Fourth Edition disadvantage: "+key);let cost=d.fixed??(d.perLevel?d.perLevel*Math.max(1,Number(levels)||1):0),detail=[];for(let i=0;i<(d.options||[]).length;i++){const group=d.options[i],choice=selections[i]??Object.keys(group.values)[0],raw=group.values[choice],rule=choiceRule(raw);if(!Number.isFinite(rule.value))throw new Error("Choose "+group.label);cost=(group.multiply||rule.multiply)?cost*rule.value:cost+rule.value;detail.push(pretty(choice));}return {key,label:d.label,levels:Number(levels)||0,selections,cost:Math.max(0,Math.round(cost)),detail:detail.join("; "),pricingBasis:"Fourth Edition",...disadvantageRolls4e(key,selections)};}
export function buildDisadvantage4e({key,name,levels=1,selections=[],notes=""}){const mechanics=calculateDisadvantage4e(key,{levels,selections});return {id:crypto.randomUUID(),tag:"CANONICAL",xmlId:key,name:name||mechanics.label,alias:mechanics.label,option:mechanics.detail,levels:Number(levels),baseCost:mechanics.cost,notes,mechanics,rawXml:""};}
export function analyzeHdcDisadvantage(rawXml){if(!rawXml)return null;const node=new DOMParser().parseFromString(rawXml,"application/xml").documentElement,id=node.getAttribute("XMLID"),map={NCM:"normalCharacteristicMaxima",UNLUCK:"unluck",PSYCHOLOGICALLIMITATION:"psychologicalLimitation",DISTINCTIVEFEATURES:"distinctiveFeatures",HUNTED:"hunted",DEPENDENTNPC:"dependentNpc",REPUTATION:"reputation",RIVALRY:"rivalry",VULNERABILITY:"vulnerability",PUBLICIDENTITY:"publicIdentity",SECRETIDENTITY:"secretIdentity",ACCIDENTALCHANGE:"accidentalChange",ENRAGED:"berserk",DEPENDENCE:"dependence",PHYSICALLIMITATION:"physicalLimitation",SUSCEPTIBILITY:"susceptibility"},key=map[id];if(!key)return {status:id==="SOCIALLIMITATION"?"later-edition-only":"unsupported",display:id==="SOCIALLIMITATION"?"Not a Fourth Edition Disadvantage; replacement required":"Fourth Edition conversion not yet implemented"};const find=(tag,xmlid)=>[...node.getElementsByTagName(tag)].find(child=>child.getAttribute("XMLID")===xmlid),option=(tag,xmlid)=>String(find(tag,xmlid)?.getAttribute("OPTIONID")||find(tag,xmlid)?.getAttribute("OPTION")||"").toUpperCase();let selections=[];
const mapValue=(value,map)=>map[value]||map[value.replaceAll("-","")]||undefined;
if(key==="accidentalChange")selections=[mapValue(option("ADDER","CIRCUMSTANCES"),{UNCOMMON:"uncommon",COMMON:"common",VERYCOMMON:"veryCommon"}),mapValue(option("ADDER","CHANCETOCHANGE"),{INFREQUENT:"8orLess",FREQUENT:"11orLess",VERYFREQUENT:"14orLess","8":"8orLess","11":"11orLess","14":"14orLess"})];
if(key==="berserk")selections=[mapValue(option("ADDER","CIRCUMSTANCES"),{UNCOMMON:"uncommon",COMMON:"common",VERYCOMMON:"veryCommon"}),mapValue(option("ADDER","CHANCETOGO"),{"8":"8orLess","11":"11orLess","14":"14orLess"}),mapValue(option("ADDER","CHANCETORECOVER"),{"14":"14orLess","11":"11orLess","8":"8orLess"}),[...node.getElementsByTagName("ADDER")].some(a=>a.getAttribute("XMLID")==="BERSERK"&&String(a.getAttribute("SELECTED")).toUpperCase()==="YES")?"berserk":"enragedOnly"];
if(key==="dependence")selections=[mapValue(option("ADDER","SUBSTANCE"),{VERYCOMMON:"veryCommon",COMMON:"common",UNCOMMON:"uncommon"}),mapValue(option("ADDER","TIME"),{SEGMENT:"segment",PHASE:"phase",TURN:"turn",MINUTE:"minute",FIVEMINUTES:"fiveMinutes",ONEHOUR:"oneHour",FIVEHOURS:"fiveHours"}),mapValue(option("ADDER","EFFECT"),{DAMAGE1D6:"1d6",DAMAGE2D6:"2d6",DAMAGE3D6:"3d6"})];
if(key==="physicalLimitation")selections=[mapValue(option("ADDER","OCCURS"),{INFREQUENTLY:"infrequently",FREQUENTLY:"frequently",ALLTHETIME:"allTheTime"}),mapValue(option("ADDER","IMPAIRS"),{SLIGHTLY:"slightly",GREATLY:"greatly",FULLY:"fully"})];
if(key==="susceptibility")selections=[mapValue(option("ADDER","CONDITION"),{UNCOMMON:"uncommon",COMMON:"common",VERYCOMMON:"veryCommon"}),mapValue(option("ADDER","DAMAGE"),{SEGMENT:"segment",PHASE:"phase",TURN:"turn",MINUTE:"minute",FIVEMINUTES:"fiveMinutes",INSTANT:"instant"}),mapValue(option("ADDER","DICE"),{"1D6":"1d6","2D6":"2d6","3D6":"3d6"})];
if(key==="psychologicalLimitation")selections=[{UNCOMMON:"uncommon",COMMON:"common",VERYCOMMON:"veryCommon"}[option("ADDER","SITUATION")],{MODERATE:"moderate",STRONG:"strong",TOTAL:"total"}[option("ADDER","INTENSITY")]];if(key==="distinctiveFeatures")selections=[{EASILY:"easilyConcealable",EASILYCONCEALABLE:"easilyConcealable",CONCEALABLE:"concealable",NOTCONCEALABLE:"notConcealable",UNCONCEALABLE:"notConcealable"}[option("ADDER","CONCEALABILITY")],{NOTICED:"noticed",MAJOR:"major",EXTREME:"extreme"}[option("ADDER","REACTION")]];if(key==="hunted")selections=[{LESS:"lessPowerful",AS:"asPowerful",MORE:"morePowerful"}[option("ADDER","CAPABILITIES")],"ordinary","unlimited",{EIGHT:"8orLess",ELEVEN:"11orLess",FOURTEEN:"14orLess"}[option("ADDER","APPEARANCE")],{MILD:"mildlyPunish",HARSH:"harshlyPunish"}[option("ADDER","MOTIVATION")]];if(key==="dependentNpc")selections=[{INCOMPETENT:"incompetent",NORMAL:"normal",SLIGHTLYLESSPOWERFUL:"slightlyLessPowerful",ASPOWERFUL:"asPowerful"}[option("ADDER","USEFULNESS")],{"8ORLESS":"8orLess","11ORLESS":"11orLess","14ORLESS":"14orLess"}[option("ADDER","APPEARANCE")],[...node.getElementsByTagName("ADDER")].some(a=>a.getAttribute("XMLID")==="USEFUL"&&String(a.getAttribute("SELECTED")).toUpperCase()==="YES")?"useful":"ordinary"];if(key==="reputation")selections=[{SOMETIMES:"sometimes",FREQUENTLY:"frequently",ALMOSTALWAYS:"almostAlways"}[option("ADDER","RECOGNIZED")],"ordinary"];if(key==="rivalry")selections=[{PROFESSIONAL:"professional",ROMANTIC:"romantic",BOTH:"both",PROFESSIONALANDROMANTIC:"both"}[option("ADDER","SITUATION")],"peer","npc"];if(key==="vulnerability")selections=[{UNCOMMON:"uncommon",COMMON:"common",VERYCOMMON:"veryCommon"}[option("ADDER","ATTACK")],{HALFSTUN:"oneAndOneHalfStun",HALFBODY:"oneAndOneHalfBody",DOUBLESTUN:"doubleStun",DOUBLEBODY:"doubleBody"}[option("MODIFIER","MULTIPLIER")]];try{return {...calculateDisadvantage4e(key,{levels:Number(node.getAttribute("LEVELS")||1),selections}),status:"converted",repricedFrom:"hero-designer-v3-5e-hdc"};}catch{return {status:"unsupported",display:"Fourth Edition options could not be verified"};}}
export function disadvantageSummary(entry){const d=entry.mechanics;if(!d)return "";if(d.status&&d.status!=="converted")return d.display||"Conversion incomplete";const rolls=[];if(Number.isFinite(d.roll))rolls.push(`${d.rollLabel||"Roll"} ${d.roll}-`);if(Number.isFinite(d.recoveryRoll))rolls.push(`${d.recoveryRollLabel||"Recovery Roll"} ${d.recoveryRoll}-`);return [d.repricedFrom?"4e repriced":"",d.detail,...rolls,d.cost+" points"].filter(Boolean).join(" · ");}
