const safeName=value=>String(value||"Hero").replace(/[<>:"/\\|?*]+/g,"-").trim()||"Hero";
const val=value=>String(value??"");
export const PRINT_SECTIONS_4E=Object.freeze([{key:"skills",label:"Skills"},{key:"perks",label:"Perks"},{key:"talents",label:"Talents"},{key:"martialarts",label:"Martial Arts"},{key:"powers",label:"Powers"},{key:"equipment",label:"Equipment"},{key:"disadvantages",label:"Disadvantages"}]);
const pointsFor=(section,entry)=>section==="equipment"&&entry.mechanics?.characterCost==null?"Campaign":Number(entry.mechanics?.realCost??entry.mechanics?.cost??entry.mechanics?.characterPoints??entry.baseCost);
const mechanicsFor=(section,entry)=>{const m=entry.mechanics||{};if(section==="powers")return [m.effect,Number.isFinite(m.activeCost)?`${m.activeCost} Active / ${m.realCost} Real`:"",(m.modifiers||[]).map(x=>x.name).join(", ")].filter(Boolean).join(" · ");if(section==="skills")return [m.detail,m.characteristic,Number.isFinite(m.roll)?`${m.roll}−`:""].filter(Boolean).join(" · ");if(section==="martialarts")return [`OCV ${m.ocv}`,`DCV ${m.dcv}`,m.action,m.effect].filter(Boolean).join(" · ");return [m.detail,entry.option].filter(Boolean).join(" · ");};
export function characterSheetRows4e(character){return PRINT_SECTIONS_4E.map(section=>({label:section.label,key:section.key,entries:(character.sections?.[section.key]||[]).map(entry=>({name:entry.name||entry.alias||"Unnamed Entry",points:pointsFor(section.key,entry),summary:mechanicsFor(section.key,entry),notes:entry.notes||""}))})).filter(section=>section.entries.length);}
const entryLine=entry=>`${entry.name}${entry.points==="Campaign"?" (campaign-priced)":Number.isFinite(entry.points)?` (${entry.points} points)`:""}${entry.summary?` — ${entry.summary}`:""}${entry.notes?` — ${entry.notes}`:""}`;
export function saveCharacterPdf(character){
 const JsPDF=window.jspdf?.jsPDF;if(!JsPDF)throw new Error("PDF engine is unavailable");
 const doc=new JsPDF({unit:"pt",format:"letter",orientation:"portrait"}),left=42,width=528,bottom=750;let y=48;
 const line=(value,size=10,bold=false,indent=0)=>{doc.setFont("helvetica",bold?"bold":"normal");doc.setFontSize(size);const parts=doc.splitTextToSize(val(value),width-indent);if(y+parts.length*(size+3)>bottom){doc.addPage();y=48;}doc.text(parts,left+indent,y);y+=parts.length*(size+3)+4;};
 if(character.portrait?.dataUrl){try{doc.addImage(character.portrait.dataUrl,undefined,466,32,104,104,undefined,"FAST");}catch{}}
 line("HERO SYSTEM FOURTH EDITION",9,true);line(character.name||"Unnamed Hero",22,true);line(`Player: ${character.playerName||"—"}`);y+=8;
 line("CHARACTER POINTS",14,true);line(`Base ${character.points?.base||0}   Maximum Disadvantages ${character.points?.disadvantages||0}   Experience ${character.points?.experience||0}`);
 line("CHARACTERISTICS",14,true);line(Object.entries(character.characteristics||{}).map(([key,value])=>`${key} ${value}`).join("   "));
 line(`BODY ${character.current?.BODY??character.characteristics?.BODY} / ${character.characteristics?.BODY}   STUN ${character.current?.STUN??character.characteristics?.STUN} / ${character.characteristics?.STUN}   END ${character.current?.END??character.characteristics?.END} / ${character.characteristics?.END}`,10,true);y+=8;
 const sheetRows=characterSheetRows4e(character);for(const section of sheetRows){line(section.label.toUpperCase(),14,true);section.entries.forEach(entry=>line(entryLine(entry),9,false,10));y+=4;}
 const p=character.profile||{};for(const [heading,value] of [["BACKGROUND",p.background],["PERSONALITY",p.personality],["TACTICS",p.tactics],["APPEARANCE",p.appearance],["NOTES",p.notes]])if(value){line(heading,14,true);line(value,9);}
 window.__hero4eLastPdf=doc.output("arraybuffer");window.__hero4eLastPdfRows=sheetRows;doc.save(`${safeName(character.name)}-HERO4E.pdf`);
}
function printHtml(character){
 const esc=value=>val(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 const content=characterSheetRows4e(character).map(section=>`<section><h2>${esc(section.label)}</h2>${section.entries.map(entry=>`<p>${esc(entryLine(entry))}</p>`).join("")}</section>`).join("");
 const stats=Object.entries(character.characteristics||{}).map(([k,v])=>`<b>${esc(k)}</b> ${esc(v)}`).join(" &nbsp; ");
 const pointLine=`Base ${character.points?.base||0} · Maximum Disadvantages ${character.points?.disadvantages||0} · Experience ${character.points?.experience||0}`;
 return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(character.name)} — HERO4E</title><style>@page{size:letter;margin:.45in}*{box-sizing:border-box}body{font:10pt Arial;color:#111;margin:0}header{border-bottom:3px solid #111;padding-bottom:8px;min-height:110px}h1{font-size:22pt;margin:2px 0;text-transform:uppercase}h2{font-size:13pt;text-transform:uppercase;border-bottom:1px solid #111;margin:12px 0 5px}p{margin:3px 0;break-inside:avoid}.portrait{float:right;width:100px;height:100px;object-fit:cover;border:2px solid #111}.stats{line-height:1.7}.points{margin:5px 0;font-weight:bold}.columns{column-count:2;column-gap:.3in}section{break-inside:avoid-column}</style></head><body><header>${character.portrait?.dataUrl?`<img class="portrait" src="${character.portrait.dataUrl}">`:""}<small>HERO SYSTEM FOURTH EDITION</small><h1>${esc(character.name||"Unnamed Hero")}</h1><div>Player: ${esc(character.playerName||"—")}</div><div class="points">${esc(pointLine)}</div><div class="stats">${stats}</div></header><main class="columns">${content}</main><script>addEventListener('load',()=>setTimeout(()=>print(),250))<\/script></body></html>`;
}
export function printCharacter(character){const popup=window.open("","_blank");if(!popup)throw new Error("Allow pop-ups to print this character");popup.document.open();popup.document.write(printHtml(character));popup.document.close();}
